object Versions {
    const val CORE_KTX = "1.7.0"
    const val JUNIT4 = "4.13.2"
    const val ESPRESSO = "3.4.0"
    const val HILT = "2.43.2"
    const val COROUTINE = "1.6.4"
    const val APPCOMPAT = "1.3.0"
    const val MATERIAL = "1.5.0"
    const val LEAKCANARY = "2.8.1"
    const val CONSTRAINT_LAYOUT = "2.1.4"
    const val FRAGMENT_KTX = "1.5.4"
    const val GLIDE = "4.12.0"
    const val RETROFIT = "2.9.0"
    const val GSON = "2.9.0"
    const val OKHTTP_INTERCEPTOR = "4.9.1"
}